name: dice
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - smbus2=0.4.3
  - pillow=10.3.0
  - Pyqt
  - langdetect
  - pip
  - pip:
    - opencv-python 
    - spidev