"""Vectorized orientation math for the DiceMaster dice.

Replaces per-tick TF lookups with direct quaternion math using NumPy/SciPy.
Loads precomputed dice geometry from YAML (generated by urdf_to_dice_config.py)
and computes all screen orientations via batch Rotation.apply() calls.

Typical usage:
    orient = DiceOrientation('resource/dice_geometry.yaml')
    result = orient.compute(imu_quaternion_xyzw)
"""

from pathlib import Path

import numpy as np
import yaml
from scipy.spatial.transform import Rotation


# Canonical face normal in the screen's local frame (screen faces +Z).
_CANONICAL_NORMAL = np.array([0.0, 0.0, 1.0])

# Edge names in fixed order, matching the YAML canonical_edges keys.
EDGE_NAMES = ('top', 'left', 'bottom', 'right')

NUM_SCREENS = 6


class DiceOrientation:
    """Compute dice screen orientations from an IMU quaternion.

    At construction time, loads the dice geometry YAML and precomputes all
    face normals, face centres, and edge offsets in the base_link frame.

    The compute() method takes a single IMU quaternion and returns orientation
    data for all 6 screens using at most two batch Rotation.apply() calls.
    """

    # Maps the lowest edge name to a rotation index (0/1/2/3).
    EDGE_TO_ROTATION = {'bottom': 0, 'right': 1, 'top': 2, 'left': 3}

    def __init__(self, config_path: str):
        """Load config and precompute geometry arrays.

        Args:
            config_path: Path to dice_geometry.yaml (absolute or relative).
        """
        cfg = self._load_config(config_path)
        self._precompute(cfg)

    # ------------------------------------------------------------------
    # Config loading
    # ------------------------------------------------------------------

    @staticmethod
    def _load_config(config_path: str) -> dict:
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f'Dice geometry config not found: {path}')
        with open(path) as f:
            return yaml.safe_load(f)

    # ------------------------------------------------------------------
    # Precomputation (runs once at startup)
    # ------------------------------------------------------------------

    def _precompute(self, cfg: dict):
        """Build all precomputed arrays from the YAML config."""
        # Screen IDs in sorted order (1..6).  We store a list so that index
        # positions are deterministic and match the rows of our arrays.
        screens_cfg = cfg['screens']
        self.screen_ids = sorted(int(k) for k in screens_cfg.keys())
        self.n_screens = len(self.screen_ids)

        # Base joint rotation: imu_link -> base_link.
        base_quat = np.array(cfg['base_joint']['quaternion'], dtype=np.float64)
        self._base_rotation = Rotation.from_quat(base_quat)

        face_offset = float(cfg['face_offset'])

        # Canonical vectors in local screen frame.
        canonical_face_offset = np.array([0.0, 0.0, face_offset])

        # Canonical edge offsets (in screen-local frame).
        canonical_edges_cfg = cfg['canonical_edges']
        # Store in EDGE_NAMES order: (4, 3)
        canonical_edge_offsets = np.array(
            [canonical_edges_cfg[e] for e in EDGE_NAMES], dtype=np.float64
        )

        # Per-screen joint rotations.
        joint_quats = np.array(
            [screens_cfg[sid]['joint_quaternion'] for sid in self.screen_ids],
            dtype=np.float64,
        )  # (N, 4)
        joint_rotations = Rotation.from_quat(joint_quats)

        # --- Face normals in base_link frame: (N, 3) ---
        # Each screen's +Z in base_link = joint_rot.apply([0,0,1]).
        normals_tiled = np.tile(_CANONICAL_NORMAL, (self.n_screens, 1))  # (N, 3)
        self._face_normals = joint_rotations.apply(normals_tiled)

        # --- Face centres in base_link frame: (N, 3) ---
        offsets_tiled = np.tile(canonical_face_offset, (self.n_screens, 1))
        self._face_centres = joint_rotations.apply(offsets_tiled)

        # --- Edge positions in base_link frame: (N, 4, 3) ---
        # For each screen, rotate the 4 canonical edge offsets by that
        # screen's joint quaternion.
        n_edges = len(EDGE_NAMES)
        self._edge_positions = np.empty(
            (self.n_screens, n_edges, 3), dtype=np.float64
        )
        for i, sid in enumerate(self.screen_ids):
            # Rotate all 4 edges in one call per screen.
            self._edge_positions[i] = joint_rotations[i].apply(canonical_edge_offsets)

        # Build reverse lookup: screen_id -> index.
        self._id_to_idx = {sid: i for i, sid in enumerate(self.screen_ids)}

    # ------------------------------------------------------------------
    # Per-tick computation
    # ------------------------------------------------------------------

    def compute(self, imu_quat: np.ndarray) -> dict:
        """Compute orientations from an IMU quaternion [x, y, z, w].

        Returns a dict with:
            'up_alignments': {screen_id: float}  -- [-1, 1] per screen
            'top_screen': int
            'bottom_screen': int
            'top_rotation': int  -- 0/1/2/3
            'face_z': {screen_id: float}  -- z of each face centre in world
            'top_edge_z': {edge_name: float}  -- z of top screen's 4 edges
        """
        # Composite rotation: world <- imu <- base_link.
        imu_rot = Rotation.from_quat(imu_quat)
        world_rot = imu_rot * self._base_rotation

        # Phase 1: batch-rotate all face normals -> extract z-component.
        world_normals = world_rot.apply(self._face_normals)  # (N, 3)
        up_alignments_arr = world_normals[:, 2]  # z-component = alignment with up

        # Face centre z positions in world frame.
        world_centres = world_rot.apply(self._face_centres)  # (N, 3)
        face_z_arr = world_centres[:, 2]

        # Top / bottom screens.
        top_idx = int(np.argmax(up_alignments_arr))
        bottom_idx = int(np.argmin(up_alignments_arr))
        top_screen = self.screen_ids[top_idx]
        bottom_screen = self.screen_ids[bottom_idx]

        # Phase 2: batch-rotate only the 4 edges of the top screen.
        top_edges_base = self._edge_positions[top_idx]  # (4, 3)
        top_edges_world = world_rot.apply(top_edges_base)  # (4, 3)
        top_edges_z = top_edges_world[:, 2]

        # Lowest edge -> rotation.
        lowest_edge_idx = int(np.argmin(top_edges_z))
        lowest_edge_name = EDGE_NAMES[lowest_edge_idx]
        top_rotation = self.EDGE_TO_ROTATION[lowest_edge_name]

        # Build result dicts keyed by screen_id.
        up_alignments = {
            sid: float(up_alignments_arr[i])
            for i, sid in enumerate(self.screen_ids)
        }
        face_z = {
            sid: float(face_z_arr[i])
            for i, sid in enumerate(self.screen_ids)
        }
        top_edge_z = {
            EDGE_NAMES[j]: float(top_edges_z[j])
            for j in range(len(EDGE_NAMES))
        }

        return {
            'up_alignments': up_alignments,
            'top_screen': top_screen,
            'bottom_screen': bottom_screen,
            'top_rotation': top_rotation,
            'face_z': face_z,
            'top_edge_z': top_edge_z,
        }

    def compute_all_edges(self, imu_quat: np.ndarray) -> dict:
        """Compute edge z positions for ALL 6 screens (validation / testing).

        Returns {screen_id: {edge_name: z_position}}.
        """
        imu_rot = Rotation.from_quat(imu_quat)
        world_rot = imu_rot * self._base_rotation

        # Flatten all edges to (N*4, 3), batch-rotate, reshape back.
        all_edges_flat = self._edge_positions.reshape(-1, 3)  # (N*4, 3)
        world_edges_flat = world_rot.apply(all_edges_flat)  # (N*4, 3)
        world_edges = world_edges_flat.reshape(self.n_screens, len(EDGE_NAMES), 3)

        result = {}
        for i, sid in enumerate(self.screen_ids):
            result[sid] = {
                EDGE_NAMES[j]: float(world_edges[i, j, 2])
                for j in range(len(EDGE_NAMES))
            }
        return result
